### ISSUE TITLE
Error when restart nginx

### ISSUE THREAD

**Issue by EnziinSystem** [ivalkeen/capistrano-nginx#9]
Capistrano-nginx is born to restart nginx but it can not do this.

I install the following:

Gemfile:

group :development do
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false
  gem 'capistrano-nginx'
end

Cap file:

require 'capistrano/deploy'
require 'capistrano/rails'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/puma'
require 'capistrano/scm/git'
require 'capistrano/nginx'

I connect to the remote server by ssh public key file.

cap production nginx:restart

rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
ruby-2.4.1
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
00:00 nginx:restart
      01 sudo service nginx restart
      01 [sudo] password for kevin:
IJIEOsdfsdw9dkksfq

It hangs at here and not anything happens.

**Comment by koenpunt** [comment]
To make this work you have to set up password-less sudo for the deploy user for certain tasks. 

For example what I generally use is:

```sudoers
Cmnd_Alias NGINX = /etc/nginx/sites-enabled/*, /usr/sbin/service nginx *, /bin/ln -sf /etc/nginx/sites-available/* /etc/nginx/sites-enabled/*, /usr/bin/unlink /etc/nginx/sites-enabled/*
deploy ALL=(ALL) NOPASSWD: NGINX
``` 

Which allows the `deploy` user to execute all `service nginx ...` tasks and allows it to delete and create symlinks

**Comment by alex-w-k** [comment]
Where do you put that snippet so you can use passwordless sudo for NGINX commands

**Comment by koenpunt** [comment]
@alex-w-k in your sudoers file. A good guide on how to edit this file can be found here: https://www.digitalocean.com/community/tutorials/how-to-edit-the-sudoers-file-on-ubuntu-and-centos
